sudo: required
services:
  - docker

before_install:
  - docker build -t sandravlado/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sandravlado/react-test npm test -- --coverage

after_success:
  - docker build -t vbundalo/multi-client ./client
  - docker build -t vbundalo/multi-nginx ./nginx
  - docker build -t vbundalo/multi-server ./server
  - docker build -t vbundalo/multi-worker ./worker

  - docker logout
  - echo "$DOCKER_PASSWORD" | docker-login -u "$DOCKER_ID" --password-stdin

  - docker push vbundalo/multi-client
  - docker push vbundalo/multi-nginx
  - docker push vbundalo/multi-server
  - docker push vbundalo/multi-worker